version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./shop.sql:/docker-entrypoint-initdb.d/shop.sql
